import type { Machine, Personnel, ScheduleDay } from './types';

export const MACHINES: Machine[] = [
  { id: '01', name: '幼幼平面口罩機1號機' },
  { id: '02', name: '成人立體L細耳2號機' },
  { id: '03', name: '小幼幼立體XXS細耳3號機' },
  { id: '05', name: '兒童立體S寬耳5號機' },
  { id: '06', name: '兒童立體S細耳6號機' },
  { id: '07', name: '幼幼立體XS寬耳7號機' },
  { id: '09', name: '成人立體L細耳新款9號機' },
  { id: '10', name: '幼幼立體XS細耳10號機' },
  { id: '11', name: '4D成人一般11號機' },
  { id: '12', name: '4D成人一般12號機' },
  { id: '13', name: '4D成人一般13號機' },
  { id: '15', name: '成人平面外耳帶15號機' },
  { id: '16', name: '4D成人一般16號機' },
  { id: '17', name: '4D成人一般17號機' },
  { id: '18', name: '4D成人加大18號機' },
  { id: '19', name: '4D幼幼19號機' },
  { id: '1FAI', name: '1樓視覺檢測' },
  { id: '20', name: '4D兒童20號機' },
  { id: '21', name: '4D兒童21號機' },
  { id: '22', name: '成人立體M細耳美顏22號機' },
  { id: '23', name: '成人立體L寬耳23號機' },
  { id: '25', name: '成人立體M細耳25號機' },
  { id: 'A3', name: '成人平面口罩機A3' },
  { id: 'A5', name: '成人平面口罩機A5' },
  { id: 'AGV', name: 'AGV自動倉儲' },
  { id: 'C8', name: '成人平面口罩機深色C8' },
  { id: 'G01', name: '成人平面口罩機G1' },
  { id: 'G02', name: '成人平面口罩機G2' },
  { id: 'G03', name: '成人平面口罩機G3' },
  { id: 'G05', name: '成人平面口罩機G5' },
  { id: 'G06', name: '成人平面口罩機G6' },
  { id: 'G07', name: '成人平面口罩機(定位)G7' },
  { id: 'G08', name: '成人平面口罩機(ACC專用)G8' },
  { id: 'G09', name: '成人平面口罩機G9' },
  { id: 'G10', name: '成人平面口罩機G10' },
  { id: 'G11', name: '兒童平面口罩機G11' },
  { id: 'G12', name: '兒童平面口罩機G12' },
  { id: 'G16', name: '成人平面小臉口罩機G16' },
];

// All personnel skills default to 'none' — can be set via the UI
function emptySkills() {
  return MACHINES.map(m => ({
    machineId: m.id,
    level: 'none' as const,
  }));
}

export const INITIAL_PERSONNEL: Personnel[] = [
  { id: 'A023', name: '阮氏合', skills: emptySkills() },
  { id: 'D004', name: '黃娃娣', skills: emptySkills() },
  { id: 'D006', name: '阮玉愛', skills: emptySkills() },
  { id: 'D010', name: '湯純真', skills: emptySkills() },
  { id: 'D012', name: '陳秋紅', skills: emptySkills() },
  { id: 'D013', name: '黃氏秋紅', skills: emptySkills() },
  { id: 'D015', name: '莊惠玲', skills: emptySkills() },
  { id: 'D016', name: '陳慧君', skills: emptySkills() },
  { id: 'D019', name: '阮瀞儀', skills: emptySkills() },
  { id: 'D021', name: '黃于庭', skills: emptySkills() },
  { id: 'D023', name: '潘子慧', skills: emptySkills() },
  { id: 'D025', name: '黎氏雪絨', skills: emptySkills() },
  { id: 'D026', name: '陳氏碧玄', skills: emptySkills() },
  { id: 'D031', name: '陳美鳳', skills: emptySkills() },
  { id: 'D033', name: '黃金鐘', skills: emptySkills() },
  { id: 'D053', name: '羅胤如', skills: emptySkills() },
  { id: 'D055', name: '黃后', skills: emptySkills() },
  { id: 'D068', name: '劉小莉', skills: emptySkills() },
  { id: 'D080', name: '裴氏妝', skills: emptySkills() },
  { id: 'D082', name: '陳采妝', skills: emptySkills() },
  { id: 'D085', name: '謝氏生', skills: emptySkills() },
  { id: 'D095', name: '林玉琴', skills: emptySkills() },
  { id: 'D103', name: '潘素娘', skills: emptySkills() },
  { id: 'D107', name: '阮嬌簪', skills: emptySkills() },
  { id: 'D124', name: '黃文泰', skills: emptySkills() },
  { id: 'D127', name: '林淑娟', skills: emptySkills() },
  { id: 'D134', name: '德麗拉', skills: emptySkills() },
  { id: 'D138', name: '玉菈', skills: emptySkills() },
  { id: 'D140', name: '麥拉', skills: emptySkills() },
  { id: 'D141', name: '武阮明書', skills: emptySkills() },
  { id: 'D143', name: '吉曼SUJIMAN', skills: emptySkills() },
  { id: 'D147', name: '武青雲', skills: emptySkills() },
  { id: 'N001', name: '麗塔ARLITA', skills: emptySkills() },
  { id: 'N002', name: '烏咪阿蒂RUMIATI', skills: emptySkills() },
  { id: 'N009', name: '南達NANDA', skills: emptySkills() },
  { id: 'N011', name: '愛迪ADE', skills: emptySkills() },
  { id: 'N013', name: '以佳IKA', skills: emptySkills() },
  { id: 'N014', name: '伊達ITA', skills: emptySkills() },
  { id: 'N033', name: '林春美', skills: emptySkills() },
  { id: 'N036', name: '范氏紅', skills: emptySkills() },
  { id: 'N038', name: '功翠榮', skills: emptySkills() },
  { id: 'N049', name: '鄧氏鸞', skills: emptySkills() },
  { id: 'N051', name: '安多WIRANTO', skills: emptySkills() },
];

const today = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Taipei' });

export const INITIAL_SCHEDULE: ScheduleDay = {
  date: today,
  leaveIds: [],
  rows: [],
};
